#!/bin/bash

# The content to be added to the profile
content="
# NVM Configuration
export NVM_DIR=\"\$HOME/.nvm\"
[ -s \"/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh\" ] && \. \"/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh\"  # This loads nvm
[ -s \"/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm\" ] && \. \"/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm\"  # This loads nvm bash_completion
"

# Function to add content to a file if it doesn't already exist
add_to_file() {
    local file=$1
    if [ -f "$file" ]; then
        if ! grep -qF "NVM Configuration" "$file"; then
            echo "$content" >> "$file"
            echo "Added NVM configuration to $file"
        else
            echo "NVM configuration already exists in $file"
        fi
    else
        echo "$file does not exist"
    fi
}


mkdir -p ~/.nvm

# Add to ~/.profile
add_to_file ~/.profile

# Add to ~/.zshrc
add_to_file ~/.zshrc

echo "Script execution completed"
